# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_STATIC_WEB_APPS_API_TOKEN with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 3. Change the values for the APP_LOCATION, API_LOCATION and APP_ARTIFACT_LOCATION, AZURE_STATIC_WEB_APPS_API_TOKEN environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: Deploy web app to Azure Static Web Apps

#2023-06-27 palun: these are all the events which trigger this script. see "if-blocks" and 
#                  in each comments from same date in each job below 
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed] 
    branches: [ "main" ]

# Environment variables available to all jobs and steps in this workflow
env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app
  REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
  REACT_APP_TENANT_ID: ${{ secrets.REACT_APP_TENANT_ID }}
  REACT_APP_URI: ${{ secrets.REACT_APP_URI }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    #2023-06-27 palun: this job runs when pushing to main and opening/reopening/sync pull requests to main. it will however
    #                  do different things in each case, ie. somehow it knows (I can't find the config for it) that when
    #                  you open a pull request it should setup a seperate enviornment (a different url) for that code, whereas
    #                  if you just push it will deploy to production. NOTE: a push happens also when you merge a pr!
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
  
      - name: Install dependencies
        run: npm install
  
      - name: Build
        run: | 
          echo "REACT_APP_CLIENT_ID=${{ env.REACT_APP_CLIENT_ID }}" > .env.prod
          echo "REACT_APP_TENANT_ID=${{ env.REACT_APP_TENANT_ID }}" >> .env.prod
          echo "REACT_APP_URI=${{ env.REACT_APP_URI }} >> .env.prod"
          
          npm run build
        env: 
          REACT_APP_CLIENT_ID: ${{ env.REACT_APP_CLIENT_ID }}
          REACT_APP_TENANT_ID: ${{ env.REACT_APP_TENANT_ID }}
          REACT_APP_URI: ${{ env.REACT_APP_URI }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    #2023-06-27 palun: this job runs when you close a pull request. NOTE: a pr is also closed when you merge it. 
    #                  it deletes the dev environment which was setup when the pull request was opened. 
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: ${{ env.APP_LOCATION }}
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing api token for app
          action: "close"
